apiVersion: v1
kind: Service
metadata:
  name: {{ include "paved-road.fullname" . }}
  labels: {{- include "paved-road.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "paved-road.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
